version: '3.8'

services:
   db:
     image: mysql:8.2.0
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: jupyterdb
       MYSQL_USER: jupyter
       MYSQL_PASSWORD: jupyterpass

   jupyter:
     depends_on:
       - db
     image: jupyter/base-notebook:latest
     ports:
       - "8888:8888"
     restart: always
     environment:
       JUPYTER_ENABLE_LAB: "yes"
       MYSQL_HOST: db
       MYSQL_USER: jupyter
       MYSQL_PASSWORD: jupyterpass
       MYSQL_DATABASE: jupyterdb
     volumes:
       - ./data:/home/jovyan/work

   mongodb:
     image: mongo:latest
     restart: always
     environment:
       MONGO_INITDB_ROOT_USERNAME: mongouser
       MONGO_INITDB_ROOT_PASSWORD: mongopass
     ports:
       - "27017:27017"
     volumes:
       - mongo_data:/data/db

volumes:
    db_data: {}
    mongo_data: {}
