version: '3.8'

services:
   db:
     image: mysql:8.2.0
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: jupyterdb
       MYSQL_USER: jupyter
       MYSQL_PASSWORD: jupyterpass

   jupyter:
     depends_on:
       - db
     image: jupyter/base-notebook:latest
     ports:
       - "8888:8888"
     restart: always
     environment:
       JUPYTER_ENABLE_LAB: "yes"
       MYSQL_HOST: db
       MYSQL_USER: jupyter
       MYSQL_PASSWORD: jupyterpass
       MYSQL_DATABASE: jupyterdb
     volumes:
       - ./data:/home/jovyan/work

   flaskapp:
     depends_on:
       - db
     image: python:3.8-slim
     volumes:
       - ./flaskapp:/usr/src/app
     working_dir: /usr/src/app
     command: flask run --host=0.0.0.0
     ports:
       - "5000:5000"
     environment:
       FLASK_APP: app.py
       FLASK_ENV: development
       DATABASE_HOST: db
       DATABASE_USER: jupyter
       DATABASE_PASSWORD: jupyterpass
       DATABASE_NAME: jupyterdb

volumes:
    db_data: {}
